#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION=""
CHECKSUMS_PATH=""
CHECKSUMS_URL=""
FORMULA_PATH="${REPO_ROOT}/packaging/homebrew/tardigrade.rb"
TAP_DIR=""

usage() {
    cat <<'EOF'
Usage: update-homebrew-formula.sh --version VERSION (--checksums PATH | --checksums-url URL) [--formula PATH] [--tap-dir DIR]

Renders packaging/homebrew/tardigrade.rb from a release checksum manifest.
When --tap-dir is provided, also writes Formula/tardigrade.rb and README.md
into a checkout of Bare-Systems/homebrew-tap.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        --checksums) CHECKSUMS_PATH="$2"; shift 2 ;;
        --checksums-url) CHECKSUMS_URL="$2"; shift 2 ;;
        --formula) FORMULA_PATH="$2"; shift 2 ;;
        --tap-dir) TAP_DIR="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [ -z "$VERSION" ]; then
    echo "--version is required" >&2
    exit 2
fi
if [ -n "$CHECKSUMS_PATH" ] && [ -n "$CHECKSUMS_URL" ]; then
    echo "use only one of --checksums or --checksums-url" >&2
    exit 2
fi
if [ -z "$CHECKSUMS_PATH" ] && [ -z "$CHECKSUMS_URL" ]; then
    echo "--checksums or --checksums-url is required" >&2
    exit 2
fi

tmpdir="$(mktemp -d)"
cleanup() {
    rm -rf "$tmpdir"
}
trap cleanup EXIT

manifest="$CHECKSUMS_PATH"
if [ -n "$CHECKSUMS_URL" ]; then
    manifest="$tmpdir/tardigrade-checksums.txt"
    curl -fsSL "$CHECKSUMS_URL" -o "$manifest"
fi
if [ ! -f "$manifest" ]; then
    echo "checksum manifest not found: $manifest" >&2
    exit 2
fi

checksum_for() {
    asset="$1"
    awk -v asset="$asset" '
        {
            path = $0
            sub(/^[[:xdigit:]]+[[:space:]]+\*?/, "", path)
            n = split(path, parts, "/")
            if (parts[n] == asset) {
                print $1
                found = 1
            }
        }
        END { if (!found) exit 1 }
    ' "$manifest"
}

validate_sha() {
    asset="$1"
    sha="$2"
    if ! printf '%s\n' "$sha" | grep -Eq '^[0-9a-f]{64}$'; then
        echo "invalid sha256 for $asset: $sha" >&2
        exit 1
    fi
}

emit_branch() {
    arch_dsl="$1"
    asset="$2"
    sha="$3"

    cat <<EOF
    ${arch_dsl} do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v${VERSION}/${asset}"
      sha256 "${sha}"
    end
EOF
}

linux_arm_asset="tardigrade-linux-aarch64.tar.gz"
linux_intel_asset="tardigrade-linux-x86_64.tar.gz"
darwin_arm_asset="tardigrade-darwin-arm64.tar.gz"
darwin_intel_asset="tardigrade-darwin-x86_64.tar.gz"

linux_arm_sha="$(checksum_for "$linux_arm_asset" || true)"
linux_intel_sha="$(checksum_for "$linux_intel_asset" || true)"
darwin_arm_sha="$(checksum_for "$darwin_arm_asset" || true)"
darwin_intel_sha="$(checksum_for "$darwin_intel_asset" || true)"

if [ -z "$linux_arm_sha" ] && [ -z "$linux_intel_sha" ] && [ -z "$darwin_arm_sha" ] && [ -z "$darwin_intel_sha" ]; then
    echo "manifest contains no Homebrew-supported Tardigrade archives" >&2
    exit 1
fi

for pair in \
    "$linux_arm_asset:$linux_arm_sha" \
    "$linux_intel_asset:$linux_intel_sha" \
    "$darwin_arm_asset:$darwin_arm_sha" \
    "$darwin_intel_asset:$darwin_intel_sha"; do
    asset="${pair%%:*}"
    sha="${pair#*:}"
    [ -z "$sha" ] || validate_sha "$asset" "$sha"
done

mkdir -p "$(dirname "$FORMULA_PATH")"
formula_tmp="$tmpdir/tardigrade.rb"

{
    cat <<EOF
# This formula is generated by scripts/update-homebrew-formula.sh.
# Canonical source: Bare-Systems/Tardigrade packaging/homebrew/tardigrade.rb

class Tardigrade < Formula
  desc "Small Zig edge server for static file serving, reverse proxying, and TLS termination"
  homepage "https://github.com/Bare-Systems/Tardigrade"
  version "${VERSION}"
  license "Apache-2.0"

EOF

    if [ -z "$darwin_arm_sha" ] && [ -z "$darwin_intel_sha" ]; then
        printf '  depends_on :linux\n\n'
    fi

    if [ -n "$darwin_arm_sha" ] || [ -n "$darwin_intel_sha" ]; then
        printf '  on_macos do\n'
        [ -z "$darwin_arm_sha" ] || emit_branch "on_arm" "$darwin_arm_asset" "$darwin_arm_sha"
        [ -z "$darwin_intel_sha" ] || emit_branch "on_intel" "$darwin_intel_asset" "$darwin_intel_sha"
        printf '  end\n\n'
    fi

    if [ -n "$linux_arm_sha" ] || [ -n "$linux_intel_sha" ]; then
        printf '  on_linux do\n'
        [ -z "$linux_arm_sha" ] || emit_branch "on_arm" "$linux_arm_asset" "$linux_arm_sha"
        if [ -n "$linux_arm_sha" ] && [ -n "$linux_intel_sha" ]; then
            printf '\n'
        fi
        [ -z "$linux_intel_sha" ] || emit_branch "on_intel" "$linux_intel_asset" "$linux_intel_sha"
        printf '  end\n\n'
    fi

    cat <<'EOF'
  def install
    bin.install "tardi"
    bin.install_symlink "tardi" => "tardigrade"
  end

  test do
    assert_match "Tardigrade", shell_output("#{bin}/tardi version")
    assert_equal (bin/"tardi").realpath, (bin/"tardigrade").realpath
  end
end
EOF
} > "$formula_tmp"

ruby -c "$formula_tmp" >/dev/null
install -m 0644 "$formula_tmp" "$FORMULA_PATH"

if [ -n "$TAP_DIR" ]; then
    mkdir -p "$TAP_DIR/Formula"
    install -m 0644 "$formula_tmp" "$TAP_DIR/Formula/tardigrade.rb"
    install -m 0644 "$REPO_ROOT/packaging/homebrew/tap-README.md" "$TAP_DIR/README.md"
fi

printf 'updated %s from %s\n' "$FORMULA_PATH" "$manifest"
if [ -n "$TAP_DIR" ]; then
    printf 'updated %s\n' "$TAP_DIR"
fi
