# This formula is generated by scripts/update-homebrew-formula.sh.
# Canonical source: Bare-Systems/Tardigrade packaging/homebrew/tardigrade.rb

class Tardigrade < Formula
  desc "Small Zig edge server for static file serving, reverse proxying, and TLS termination"
  homepage "https://github.com/Bare-Systems/Tardigrade"
  version "0.5.0"
  license "Apache-2.0"

  depends_on :linux

  on_linux do
    on_arm do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.5.0/tardigrade-linux-aarch64.tar.gz"
      sha256 "204cd9c85dfc225a68704eab7b20d900b8ddaa7df8da123463e4a969cb569c38"
    end

    on_intel do
      url "https://github.com/Bare-Systems/Tardigrade/releases/download/v0.5.0/tardigrade-linux-x86_64.tar.gz"
      sha256 "0d81db140b18bf3a717923416f83009285d267b5bc9e99132e51f210a5447b4d"
    end
  end

  def install
    bin.install "tardi"
    bin.install_symlink "tardi" => "tardigrade"
  end

  test do
    assert_match "Tardigrade", shell_output("#{bin}/tardi version")
    assert_equal (bin/"tardi").realpath, (bin/"tardigrade").realpath
  end
end
