const std = @import("std");

/// Canonical first-run config profiles generated by `tardi init <profile>`
/// and `tardi config init --profile <profile>`. Every profile has exactly
/// one template; descriptive aliases (see `parse`) resolve to the same
/// canonical value and therefore the same template bytes.
pub const ConfigProfile = enum {
    static,
    proxy,
    tls,
    metrics,
    prod,
};

pub const all = [_]ConfigProfile{ .static, .proxy, .tls, .metrics, .prod };

const Alias = struct {
    name: []const u8,
    profile: ConfigProfile,
};

// Exact, lowercase-only matches -- no prefix/fuzzy matching (#162), so a
// typo fails loudly instead of silently resolving to the wrong profile.
const aliases = [_]Alias{
    .{ .name = "static", .profile = .static },
    .{ .name = "static-site", .profile = .static },
    .{ .name = "proxy", .profile = .proxy },
    .{ .name = "reverse-proxy", .profile = .proxy },
    .{ .name = "tls", .profile = .tls },
    .{ .name = "tls-termination", .profile = .tls },
    .{ .name = "metrics", .profile = .metrics },
    .{ .name = "metrics-enabled", .profile = .metrics },
    .{ .name = "prod", .profile = .prod },
    .{ .name = "production-baseline", .profile = .prod },
};

/// Resolves a canonical profile name or descriptive alias. Returns null for
/// anything else, including case variants -- callers report those as an
/// unknown profile rather than guessing.
pub fn parse(name: []const u8) ?ConfigProfile {
    for (aliases) |alias| {
        if (std.mem.eql(u8, alias.name, name)) return alias.profile;
    }
    return null;
}

pub fn canonicalName(profile: ConfigProfile) []const u8 {
    return switch (profile) {
        .static => "static",
        .proxy => "proxy",
        .tls => "tls",
        .metrics => "metrics",
        .prod => "prod",
    };
}

pub fn descriptiveAlias(profile: ConfigProfile) []const u8 {
    return switch (profile) {
        .static => "static-site",
        .proxy => "reverse-proxy",
        .tls => "tls-termination",
        .metrics => "metrics-enabled",
        .prod => "production-baseline",
    };
}

pub fn template(profile: ConfigProfile) []const u8 {
    return switch (profile) {
        .static => static_template,
        .proxy => proxy_template,
        .tls => tls_template,
        .metrics => metrics_template,
        .prod => prod_template,
    };
}

/// A comma-separated list of canonical profile names, for "unknown profile"
/// and usage/help output.
pub const canonical_names_csv = "static, proxy, tls, metrics, prod";

const static_template =
    \\# Tardigrade profile: static
    \\# Serves files from ./public with an SPA fallback.
    \\# Validate with: tardi check ./tardigrade.conf
    \\
    \\listen 8080;
    \\server_name localhost;
    \\
    \\root ./public;
    \\try_files $uri /index.html;
    \\
    \\location = /health {
    \\    return 200 ok;
    \\}
    \\
    \\location / {
    \\    root ./public;
    \\    try_files $uri /index.html;
    \\}
    \\
;

const proxy_template =
    \\# Tardigrade profile: proxy
    \\# Replace 127.0.0.1:3000 with your application upstream.
    \\
    \\listen 8080;
    \\server_name localhost;
    \\
    \\location = /health {
    \\    return 200 ok;
    \\}
    \\
    \\location / {
    \\    proxy_pass http://127.0.0.1:3000;
    \\}
    \\
;

const tls_template =
    \\# Tardigrade profile: tls
    \\# Provision these certificate files before running `tardi check`.
    \\# Never commit private keys into source control.
    \\
    \\listen 8443 ssl;
    \\server_name localhost;
    \\
    \\tls_cert_path /etc/tardigrade/tls/fullchain.pem;
    \\tls_key_path /etc/tardigrade/tls/privkey.pem;
    \\
    \\location = /health {
    \\    return 200 ok;
    \\}
    \\
    \\location / {
    \\    proxy_pass http://127.0.0.1:3000;
    \\}
    \\
;

const metrics_template =
    \\# Tardigrade profile: metrics
    \\#
    \\# Prometheus metrics are available at /status/metrics by default.
    \\# Production deployments should either:
    \\#   - set TARDIGRADE_METRICS_REQUIRE_AUTH=true, or
    \\#   - restrict the metrics endpoint at the network boundary.
    \\
    \\listen 8080;
    \\server_name localhost;
    \\
    \\location = /health {
    \\    return 200 ok;
    \\}
    \\
    \\location / {
    \\    proxy_pass http://127.0.0.1:3000;
    \\}
    \\
;

const prod_template =
    \\# Tardigrade profile: prod
    \\#
    \\# Production baseline -- NOT deploy-ready until the values below and the
    \\# documented environment settings are reviewed for your deployment.
    \\#
    \\# Required:
    \\#   - provision a real TLS certificate/private key
    \\#   - configure the real upstream (TARDIGRADE_UPSTREAM_BASE_URL)
    \\#   - restrict/authenticate metrics (TARDIGRADE_METRICS_REQUIRE_AUTH)
    \\#
    \\# Recommended production settings include security headers, HSTS, rate
    \\# limiting, JSON access logging, active upstream health checks, bounded
    \\# timeouts, and graceful drain. See examples/production-baseline/ for the
    \\# full checklist and environment reference.
    \\
    \\listen 8443 ssl;
    \\server_name localhost;
    \\
    \\tls_cert_path /etc/tardigrade/tls/fullchain.pem;
    \\tls_key_path /etc/tardigrade/tls/privkey.pem;
    \\
    \\location = /health {
    \\    return 200 ok;
    \\}
    \\
    \\location / {
    \\    proxy_pass /;
    \\}
    \\
;

test "every canonical profile parses from its own canonical name" {
    for (all) |profile| {
        try std.testing.expectEqual(profile, parse(canonicalName(profile)).?);
    }
}

test "every descriptive alias resolves to its canonical profile" {
    for (all) |profile| {
        try std.testing.expectEqual(profile, parse(descriptiveAlias(profile)).?);
    }
}

test "aliases produce byte-identical output to the canonical profile" {
    for (all) |profile| {
        const canonical_bytes = template(profile);
        const alias_profile = parse(descriptiveAlias(profile)).?;
        try std.testing.expectEqualStrings(canonical_bytes, template(alias_profile));
    }
}

test "unknown profile names do not parse" {
    try std.testing.expectEqual(@as(?ConfigProfile, null), parse("kubernetes"));
    try std.testing.expectEqual(@as(?ConfigProfile, null), parse(""));
    try std.testing.expectEqual(@as(?ConfigProfile, null), parse("Static"));
    try std.testing.expectEqual(@as(?ConfigProfile, null), parse("stat"));
}

test "every template is deterministic and newline-terminated" {
    for (all) |profile| {
        const bytes = template(profile);
        try std.testing.expect(bytes.len > 0);
        try std.testing.expect(std.mem.endsWith(u8, bytes, "\n"));
        try std.testing.expectEqualStrings(bytes, template(profile));
    }
}

test "templates contain no embedded private key material" {
    for (all) |profile| {
        const bytes = template(profile);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "BEGIN") == null);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "PRIVATE KEY") == null);
    }
}

test "static and proxy profiles have no TLS prerequisite" {
    for ([_]ConfigProfile{ .static, .proxy, .metrics }) |profile| {
        const bytes = template(profile);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "tls_cert_path") == null);
    }
}

test "tls and prod profiles enable TLS with placeholder credential paths" {
    for ([_]ConfigProfile{ .tls, .prod }) |profile| {
        const bytes = template(profile);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "listen 8443 ssl;") != null);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "tls_cert_path /etc/tardigrade/tls/fullchain.pem;") != null);
        try std.testing.expect(std.mem.indexOf(u8, bytes, "tls_key_path /etc/tardigrade/tls/privkey.pem;") != null);
    }
}

test "metrics profile names the existing metrics endpoint" {
    const bytes = template(.metrics);
    try std.testing.expect(std.mem.indexOf(u8, bytes, "/status/metrics") != null);
    try std.testing.expect(std.mem.indexOf(u8, bytes, "TARDIGRADE_METRICS_REQUIRE_AUTH") != null);
}
